name: User Approval Workflow
on:
  push:
    branches:
      - master
jobs:
  stage-1-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 1
        run: echo "Stage 1"

  stage-2-echo:
    needs: stage-1-echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 2
        run: echo "Stage 2"

  staging-approval-gate:
    needs: stage-2-echo
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: approved
        env: 
          ENV_NAME: ashok
        run: write-host "Approve for $(NPM_TOKEN)"
