name: User Approval Workflow

on:
  push:
    branches:
      - master

jobs:
  stage-1-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 1
        run: echo "Stage 1"

  stage-2-echo:
    needs: stage-1-echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 2
        run: echo "Stage 2"

  create-user:
    needs: stage-2-echo
    runs-on: ubuntu-latest
    steps:
      - name: Create User
        run: echo "Create User"

  manual-approval:
    needs: create-user
    runs-on: ubuntu-latest
    steps:
      - name: 'Request approval'
        id: approval
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.NPM_TOKEN }}
          script: |
            const { data: { html_url } } = await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            });
            return html_url;

  run-if-approved:
    needs: manual-approval
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'submitted' && github.event.review.state == 'approved'
    steps:
      - name: Echo Stage 3 (if approved)
        run: echo "Stage 3 (if approved)"
        env:
          ENV_VARIABLE_NAME: "NPM_TOKEN"

  run-if-rejected:
    needs: manual-approval
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'submitted' && github.event.review.state == 'changes_requested'
    steps:
      - name: Echo Stage 3 (if rejected)
        run: echo "Stage 3 (if rejected)"
