name: User Approval Workflow

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploying..."

  approval:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Request approval
        id: approval
        uses: "actions/github-script@v5"
        with:
          script: |
            const { data: approvals } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const existingApproval = approvals.find(approval => approval.user.login === "username");
            if (!existingApproval) {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                event: "APPROVE"
              });
            }
