name: Build and User Approval Workflow

on:
  push:
    branches:
      - master

jobs:
  stage-1-echo:
    runs-on: self-hosted
    steps:
      - name: Echo Stage 1
        run: echo "Stage 1"

  Dev-Env:
    name: deploy
    runs-on: self-hosted
    needs: stage-1-echo
    steps:
      - uses: ashoklogicfocus/samplekube@v1
        with:
          secret: ${{ secrets.NEW_TOKEN }}
          approvers: trstringer,acdunnigan
          minimum-approvals: 1
          issue-title: 'Approval Required for Deployment'
          issue-body: 'Please review and approve this deployment.'
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

  Pre-env:
    runs-on: self-hosted
    if: ${{ github.event.review.status == 'approved' }}
    needs: Dev-Env
    steps:
      - name: 'Run approved steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work'
  Pr-as:
    runs-on: self-hosted
    if: ${{ github.event.review.status != 'approved' }}
    needs:  Dev-Env
    steps:
      - name: 'Run not approved steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work' 
