name: Manual Approval Demo

on:
  workflow_dispatch:
    
jobs:
  Pre-Dev-Steps:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Run some predev steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work'
