name: User Approval Workflow

on:
  push:
    branches:
      - master

jobs:
  stage-1-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 1
        run: echo "Stage 1"

  stage-2-echo:
    needs: stage-1-echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 2
        run: echo "Stage 2"

  create-user:
    runs-on: ubuntu-latest
    needs: stage-2-echo
    steps:
      - name: Create User
        run: echo "Creating User"
  
  user-approval:
    runs-on: ubuntu-latest
    needs: create-user
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Request approval
        uses: actions/github-script@v5
        with:
          script: |
            const { data: approvals } = await octokit.rest.actions.listRepoWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: context.workflow,
              branch: context.ref.split('/').pop(),
              per_page: 1,
              page: 1,
            });
            if (approvals.workflow_runs.length > 0) {
              const runId = approvals.workflow_runs[0].id;
              await octokit.rest.actions.createWorkflowRunApproval({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: runId,
                approval_requester: context.actor,
              });
            } else {
              console.log("No workflow run found to approve.");
            }
