name: Build and User Approval Workflow

on:
  push:
    branches:
      - master

jobs:
  Pre-Dev-Steps:
    runs-on: self-hosted

    steps:
      - name: 'Run some predev steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work'

  Dev-Env:
    name: deploy
    runs-on: self-hosted
    needs: Pre-Dev-Steps
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.NEW_TOKEN }}
          approvers: trstringer,acdunnigan
      - name: Deploy to production
        run: echo deploying

  Pre-env:
    runs-on: self-hosted
    if: ${{ github.event.review.status == 'approved' }}
    needs: Dev-Env
    steps:
      - name: 'Run approved steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work'
  Pr-as:
    runs-on: self-hosted
    if: ${{ github.event.review.status != 'approved' }}
    needs:  Dev-Env
    steps:
      - name: 'Run not approved steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work' 
