name: Build and User Approval Workflow

on:
  push:
    branches:
      - master

jobs:
  Pre-Dev-Steps:
    runs-on: ubuntu-latest

    steps:
      - name: 'Run some predev steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work'

  Dev-Env:
    runs-on: ubuntu-latest
    needs: Pre-Dev-Steps
    environment:
      name: DEVENV
    steps:
      - name: 'Run some dev env steps'
        shell: pwsh
        run: |
          Write-Host 'Done some dev env deploy work'

  User-Approval:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: Dev-Env
    steps:
      - name: 'Manual approval required'
        id: approval
        uses: tzkhan/approvals@v2
        with:
          message: 'Approve or reject this deployment.'
      - name: 'Check approval status'
        if: steps.approval.outputs.approved == 'true'
        run: |
          Write-Host 'Deployment approved. Proceeding with deployment.'
          # Add your deployment steps here
      - name: 'Handle rejection'
        if: steps.approval.outputs.approved != 'true'
        run: |
          Write-Host 'Deployment rejected. Stopping the workflow.'

