name: Build and User Approval Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Application
        run: |
          echo "Building Application"

  user_approval:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Request User Approval
        id: approval
        uses: myorg/my-approval-action@v1
        with:
          message: "Do you approve this build?"
      - name: Check Approval
        run: |
          if [[ "${{ steps.approval.outputs.approved }}" == "yes" ]]; then
            echo "User approved the build"
          else
            echo "User did not approve the build"
            exit 1
          fi
