name: Build and User Approval Workflow

on:
  push:
    branches:
      - master

jobs:
  Pre-Dev-Steps:
    runs-on: ubuntu-latest

    steps:
      - name: 'Run some predev steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work'

  Dev-Env:
    name: deploy
    runs-on: ubuntu-latest
    needs: Pre-Dev-Steps
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.NEW_TOKEN }}
          approvers: trstringer,acdunnigan
          minimum-approvals: 1
          issue-title: 'Approval Required for Deployment'
          issue-body: 'Please review and approve this deployment.'
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

  Pre-env:
    runs-on: ubuntu-latest
    if: ${{ github.event.review.status == 'approved' }}
    needs: Dev-Env
    steps:
      - name: 'Run approved steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work'
  Pr-as:
    runs-on: ubuntu-latest
    if: ${{ github.event.review.status != 'approved' }}
    needs:  Dev-Env
    steps:
      - name: 'Run not approved steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work' 
