name: User Approval Workflow
on:
  push:
    branches:
      - master
jobs:
  stage-1-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 1
        run: echo "Stage 1"
  stage-2-echo:
    needs: stage-1-echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 2
        run: echo "Stage 2"
  stage-3-create-user:
    needs: stage-2-echo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        approve-user: [true]
      fail-fast: true
    steps:
      - name: Create User
        id: create-user
        run: echo "User creation logic here"
        continue-on-error: true
      - name: Set Approval Flag
        if: ${{ always() }}
        run: echo "::set-output name=approve-user::false"
  stage-4-approve:
    needs: stage-3-create-user
    runs-on: ubuntu-latest
    if: ${{ needs.stage-3-create-user.outputs.approve-user == 'true' }}
    steps:
      - name: Approve User
        run: echo "User approved"
  stage-5-reject:
    needs: stage-3-create-user
    runs-on: ubuntu-latest
    if: ${{ needs.stage-3-create-user.outputs.approve-user != 'true' }}
    steps:
      - name: Reject User
        run: echo "User rejected"
  stage-6-manual-approval:
    needs: [stage-4-approve, stage-5-reject]
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: user1,user2,org-team1
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
