name: User Approval Workflow
on:
  push:
    branches:
      - master
jobs:
  stage-1-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 1
        run: echo "Stage 1"
  stage-2-echo:
    needs: stage-1-echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 2
        run: echo "Stage 2"
  stage-3-create-user:
    needs: stage-2-echo
    runs-on: ubuntu-latest
    steps:
      - name: ashok
        run: |
         # Your user creation logic here
      # Add other steps here

      # This step will only run if the previous step's output is 'true'
      - name: Conditional step
        if: steps.create-user.outputs.result == 'true'
        run: |
          # Your conditional logic here
          
  stage-4-approve:
    if: failure()
    needs: stage-3-create-user
    runs-on: ubuntu-latest
    steps:
      - name: Reject User
        run: |
          # Script to reject user
          # Assuming it's a placeholder
  stage-5-reject:
    if: success()
    needs: stage-3-create-user
    runs-on: ubuntu-latest
    steps:
      - name: Approve User
        run: |
          # Script to approve user
          # Assuming it's a placeholder
