name: Build and User Approval Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Application
        run: |
          echo "Building Application" 

  user_approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Request User Approval
        run: echo "Requesting User Approval"
