name: User Approval Workflow
on:
  push:
    branches:
      - master
jobs:
  stage-1-echo:
    runs-on: self-hosted
    steps:
      - name: Echo Stage 1
        run: echo "Stage 1"
  manual-approval:
    runs-on: self-hosted
    needs: stage-1-echo
    steps:
      - name: Manual Approval
        uses: macnev2013/manual-approval@latest
        with:
          secret: ${{ github.TOKEN }}
          approvers: user1,user2
          minimum-approvals: 1
          approval-wait: 600
          issue-title: 'Manual Approval'
          issue-body: |
            "Issue Body"
  stage-2-echo:
    needs: manual-approval
    runs-on: self-hosted
    steps:
      - name: Echo Stage 2
        run: echo "Stage 2"
