name: Manual Approval Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."

      - name: Approve
        if: github.actor == 'approved-user'
        id: approve
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            if (pullRequest.user.login === 'approved-user') {
              return { approved: true };
            } else {
              return { approved: false };
            }

  deploy:
    needs: build
    runs-on: self-hosted
    if: needs.build.outputs.approve == 'true'

    steps:
      - name: Deploy
        run: echo "Deploying..."
