name: User Approval Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: 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
          approvers: trstringer,acdunnigan
      - name: Deploy to production
        run: echo deploying
